CREATE TABLE IF NOT EXISTS snippets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  category TEXT NOT NULL,
  tags TEXT NOT NULL DEFAULT '[]',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS draft_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  customer_message TEXT NOT NULL,
  draft_reply TEXT NOT NULL,
  snippet_ids TEXT NOT NULL,
  model TEXT NOT NULL,
  latency_ms INTEGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
